### ISSUE TITLE
[Bug] Updating the topic for the pubsub subscription not reflected

### ISSUE THREAD

**Issue by mmyoussef** [goblet/goblet#319]
Changed the env variables from
```
"env": [
                    {
                         "name":"xxxxxx_SERVICE_ENV",
                         "value": "prod"
                    },
                    {
                        "name": "ENV_PROJECT",
                        "value": "xxxxxx-prod"
                    },
                    {
                        "name": "IS_DRYRUN",
                        "value": "1"
                    },
                    {
                        "name": "REDIS_HOST",
                        "value": "xxxxxxxxx"
                    },
                    {
                        "name": "REDIS_PORT",
                        "value": "xxxx"
                    },
                    {
                        "name": "xxxxxx",
                        "value": "xxxxxxx"
                    },
                    {
                        "name": "PUBSUB_PROJECT",
                        "value": "xxxx-prod"
                    }
                ]
```

```
"env": [
                    {
                         "name":"xxxxxx_SERVICE_ENV",
                         "value": "qa"
                    },
                    {
                        "name": "ENV_PROJECT",
                        "value": "xxxxxx-qa"
                    },
                    {
                        "name": "IS_DRYRUN",
                        "value": "1"
                    },
                    {
                        "name": "REDIS_HOST",
                        "value": "xxxxxxxxx"
                    },
                    {
                        "name": "REDIS_PORT",
                        "value": "xxxx"
                    },
                    {
                        "name": "xxxxxx",
                        "value": "xxxxxxx"
                    },
                    {
                        "name": "PUBSUB_PROJECT",
                        "value": "xxxxx-qa"
                    }
                ]
```

The subscription was not updated to the QA topic and remained with the PROD topic. I had to delete the subscription to be updated to the QA topic

**Comment by anovis** [comment]
interesting. let me look into it. i am not sure if it is [supported by gcp to change the topic of a subscription](https://cloud.google.com/pubsub/docs/reference/rest/v1/projects.subscriptions/patch), although it looks possible based on the docs. 
one difficulty is that we use the topic as part of the subscription name ```f"{self.name}-{topic_name}"```.
Although by changing the topic name it should have created a new subscription and left the old one. 

let me investigate.

**Comment by anovis** [comment]
@mmyoussef i ended up running into this today 🤦 . 

the problem is that the cross project subscriptions are created in the same project that the clodurun exists. so when we update the subscription to a new project, it actually keeps the same subscription name. 

and when we try to update it we actually remove the key `keys.remove("topic")` since we can't update that. 


```
    try:
        client.execute(
            "create",
            parent_key="name",
            parent_schema="projects/{project_id}/subscriptions/" + sub_name,
            params={"body": req_body},
        )
        log.info(f"creating pubsub subscription {sub_name}")
    except HttpError as e:
        if e.resp.status == 409:
            log.info(f"updating pubsub subscription {sub_name}")
            # Setup update mask
            keys = list(req_body.keys())
            # Remove keys that cannot be updated
            keys.remove("name")
            keys.remove("topic")
```

what I will need to do is to check if the project is different and then delete the old one and create the new one.

**Comment by anovis** [comment]
Since the names are the same between topics of the same name and different projects there is no way to create a different subscription without either deleting the old one, or making a breaking change to the existing naming structure of topics. 

instead what i propose is that if we run into this case we will log to the user that a subscription for a different project and same name exists.

additionally we will add a flag to topic function `force_update` that when set to true will delete to existing topic and create the new one
