### ISSUE TITLE
PUT request getting blocked by CORS

### ISSUE THREAD

**Issue by iaudouard** [goblet/goblet#469]
I have a route that was getting blocked by CORS when it was set as a PUT method, but worked as a POST. My fix was to add the following header into the `get_access_control_headers` method of the `CORSConfig` class:

```json
"Access-Control-Allow-Methods": "GET, POST, PUT, DELETE, PATCH, OPTIONS"
```

Putting it manually into a headers kwarg for the route did _not_ work.

**Comment by anovis** [comment]
The cors standard ```A CORS-safelisted method is a [method](https://fetch.spec.whatwg.org/#concept-method) that is `GET`, `HEAD`, or `POST`.``` (https://fetch.spec.whatwg.org/#methods) which is why the PUT was not working. 

And it would not work on the method manually, since CORS happens on a preflight OPTIONS request. 

I will add ability to pass in `Access-Control-Allow-Methods` dynamically as well as any other headers, so it is easier to customize in the future.
